name: Documentation

on:
  push:
    branches: ["main"]  # or your default branch

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -e .[doc]

      - name: Build the Sphinx documentation
        run: |
          cd doc
          make html

      - name: Upload HTML to GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/build/html  # Adjust if your output is elsewhere

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4