name: "Testing on push"

on:
  push:
    branches:
      - '*'

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Continue testing other jobs even if one fails
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install .[dev]
      - run: python -m pytest tests/

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Black
        run: python -m pip install black
      - name: Check formatting with Black
        run: python -m black --check ssm/ tests/
